name: Build and Validate

on:
    push:
        branches:
            - "**"
    
    workflow_dispatch:

permissions:
    contents: read

jobs:
    build-validate-image:
        name: Build the Docker image and validate the entrypoint
        runs-on: [ macos-latest ]
        steps:
            - name: checkout source code
              uses: actions/checkout@v4

            - name: Build Image
              run: |
                echo ${{ secrets.GH_PACKAGE_ACCESS_TOKEN }} | docker login ghcr.io -u nhendri --password-stdin
                docker build -t local/ansible:gha-workflow .
                docker logout

            - name: Prune Image
              run: |
                docker rmi -f $(docker images --format "{{.ID}}" local/ansible:gha-workflow) && docker image prune -f
